### ISSUE TITLE
help me in aiml please

### ISSUE THREAD

**Issue by walide67** [AIML-Bots/aiml-java-interpreter#2]
hi 
how i can to displaye a value of javascript variable in the template aiml??
```
<category>
<pattern>
i search *
</pattern>
<template>
<think>
<set name="mot"><star/></set>
</think>
<script language="JavaScript">
var mot='<star/>';
bot_recherche(mot);
</script>
</template>
</category>
```
i want to display the value of ` bot_recherche(mot)`

**Comment by batiaev** [comment]
Hello, man, sorry for delay.

This interpreter based on [AIML 2.0 Working Draft](https://docs.google.com/document/d/1wNT25hJRyupcG51aO89UcQEiG-HkXRXusukADpFnDs4/pub) specification which says that does not have to support a scripting language such as JavaScript.

Perhaps some other interpreters can help you with this. Or you can always create this functionality by yourself
